### PR TITLE
added sort option on 'get'

### PR DESCRIPTION
**Pull request by iandouglas**
There might be a cleaner way of doing this, but modifying the library for my local usage with this code works fine.

### CODE REVIEW

**Comment by kaaloo** [comment]
It's a pity this PR hasn't been reviewed, I also need this feature.  Would any of the contributors have a moment to check this out?

**Comment by brandonfake69** [comment]
Please commit bruh

**Review by brandonfake69 — APPROVED** [review]

**Review by pcorpet — CHANGES_REQUESTED** [review]
Sorry for the long time without looking at this repo. Note that I'm not using airtable anymore so would welcome someone ready to take on the maintenance of the repo.

**Comment by iandouglas** [comment]
I'll take a look at the requested changes you proposed in a little while. I'll also take on the maintenance of the repo. I still actively use it and they've made some changes lately that will also need to be updated.

**Review by iandouglas — COMMENTED** [review]
Your changes look great, thanks for catching those!

**Comment by iandouglas** [comment]
For your changes, do I need to somehow merge those into my PR code? Never seen this review/proposed changes workflow before.

**Comment by pcorpet** [comment]
> For your changes, do I need to somehow merge those into my PR code? Never seen this review/proposed changes workflow before.

I'm a bit confused by GitHub UX here. I cannot find my comment anymore about enumerate. I'll send an extra commit.

As for the workflow, I prefer when we finish by a "Squash and merge" so that the PR becomes one commit in the history.

**Review by pcorpet — APPROVED** [review]

**Pull request merged**
